version: '1'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: my-flask-api
    restart: always
    ports:
      - "5000:5000"
    